apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
        - name: python-webapp
          image: webapp:2.0     # Change this to your image if pushed, e.g. yourdockerid/webapp:2.0
          ports:
            - containerPort: 5000
